### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Coder108** [wodin/logicaldoc#1]
Hello, I don't know how to deploy to Tomcat. Can you help me? Can you send a tutorial to my email ?  

1083170596@qq.com thanks!

**Comment by wodin** [comment]
Hi. I am not involved with the logicaldoc project. This repository is an unofficial copy of the repository on Source Forge.
Please go here for help:
https://wiki.logicaldoc.com/wiki/Main_Page
https://forums.logicaldoc.com/
